# Generated by Django 3.2.16 on 2024-01-05 15:36

from django.db import migrations

from core.utils import insert_role_right_for_system, remove_role_right_for_system


REPORT_NHIA_NEW_ENROLLMENTS_RIGHT = 131227
REPORT_NHIA_NON_ACTIVE_MEMBERS_RIGHT = 131228
REPORT_NHIA_POLICY_RENEWALS_RIGHT = 131229
NHIA_REPORT_RIGHTS = [
    REPORT_NHIA_NEW_ENROLLMENTS_RIGHT,
    REPORT_NHIA_NON_ACTIVE_MEMBERS_RIGHT,
    REPORT_NHIA_POLICY_RENEWALS_RIGHT
]
SYSTEM_ROLE = 64


def add_nhia_report_rights(apps, schema_editor):
    """
    Add nhia report rights to the IMIS Administrator.
    """
    for right in NHIA_REPORT_RIGHTS:
        insert_role_right_for_system(SYSTEM_ROLE, right)


def remove_nhia_reports_rights(apps, schema_editor):
    """
    Remove nhia report rights to the IMIS Administrator.
    """
    for right in NHIA_REPORT_RIGHTS:
        remove_role_right_for_system(SYSTEM_ROLE, right)


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0008_policyrenewalmutation'),
    ]

    operations = [
        migrations.RunPython(add_nhia_report_rights, remove_nhia_reports_rights),
    ]
